### ISSUE TITLE
about odometry format in the dataset

### ISSUE THREAD

**Issue by weiningwei** [kminoda/VIODE#10]
I save the data of odometry topic to a txt file. Then I plot data of x-y axis. But the figure is different from the groundtruth in your paper. The x-y axia data is the opposite. My plot figures and the paper's groundtruth are as follows:

![x-y](https://user-images.githubusercontent.com/38557780/137680572-ddb8134f-4dac-4320-8592-faa4257e124e.png)
![y-x](https://user-images.githubusercontent.com/38557780/137680582-db8d6107-6a5c-4a1a-88f3-d4c067470825.png)
![paper](https://user-images.githubusercontent.com/38557780/137680877-897ca286-9b14-462a-a787-843851b596b9.png)

I am confused about this.

**Comment by kminoda** [comment]
Thank you for the feedback. As a quick response, it's probably because that the coordinates have been modified during the evaluation. I will take a look into it and give you further response later.

I assume that it would not be a critical issue for the users of this dataset nor the arguments in the paper, but let me know if you have any further problems related to this.
